name: filestash-h31
version: git
summary: A modern web client for SFTP, S3, FTP, WebDAV, Git, LDAP, Backblaze, ...
description: |
    Filestash is web application that's used as a file manager to manage your data using: FTP • FTPS • SFTP • WebDAV • Git • S3 • LDAP • Mysql • CardDAV • CalDAV • Backblaze B2 • Minio • Dropbox • Google Drive
grade: stable
confinement: strict
base: core18

parts:
    frontend:
        plugin: nil
        source-type: git
        source: https://github.com/h31/filestash
        source-depth: 1
        source-branch: "packages"
        build-packages:
            - make
        build-snaps:
            - node/12/stable
        override-build: |
            PATH=$(pwd)/../npm/bin:$PATH
            unset SUDO_UID
            unset SUDO_GID
            npm --unsafe-perm install
            NODE_ENV=production npm --unsafe-perm run build
            cp -R ./dist/data $SNAPCRAFT_PART_INSTALL/
            mkdir -p $SNAPCRAFT_PART_INSTALL/bin/data/state/
            cp -R config $SNAPCRAFT_PART_INSTALL/bin/data/state/

    libvips:
        plugin: autotools
        source-type: git
        source: https://github.com/libvips/libvips
        source-tag: v8.7.0
        source-depth: 1
        build-packages:
            - build-essential
            - pkg-config
            - libglib2.0-dev
            - swig
            - flex
            - bison
            - bc
            - gobject-introspection
            - libjpeg-dev
            - libtiff-dev
            - libpng-dev
            - libgif-dev
            - librsvg2-dev
            - libpoppler-glib-dev
            - zlib1g-dev
            - liblzma-dev
            - libfftw3-dev
            - liblcms2-dev
            - libmagickcore-dev
            - libmagickwand-dev
            - libfreetype6-dev
            - libpango1.0-dev
            - libfontconfig1-dev
            - libice-dev
            - gettext
            - libxml-parser-perl
            - libexif-gtk-dev
            - python3-all-dev
            - python3-dev
            - python-gi-dev
            - liborc-0.4-dev
            - libopenexr-dev
            - libmatio-dev
            - libexpat1-dev
            - libcfitsio-dev
            - libopenslide-dev
            - libwebp-dev
            - libgsf-1-dev
            - libgirepository1.0-dev
            - gtk-doc-tools
        stage-packages:
            - libgsf-1-114
            - libicu60
            - libpng16-16
            - libxml2
            - libexif12
            - libfftw3-double3
            - libgif7
            - libjbig0
            - libjpeg-turbo8
            - liborc-0.4-0
            - libtiff5
        configflags:
            - --enable-static
            - --without-magick
            - --without-lcms
            - --without-OpenEXR
            - --without-nifti
            - --without-pdfium
            - --without-rsvg
            - --without-matio
            - --without-libwebp
            - --without-cfitsio
            - --without-zlib
            - --without-poppler
            - --without-pangoft2
            - --enable-introspection=no
            - --without-openslide

    backend:
        plugin: go
        source-type: git
        source: https://github.com/h31/filestash
        source-depth: 1
        source-branch: "packages"
        after:
            - libvips
        build-packages:
            - build-essential
            - pkg-config
            - libraw-dev
        stage-packages:
            - libexif12
            - libfftw3-double3
            - libgif7
            - libgomp1
            - libjbig0
            - libjpeg-turbo8
            - liblcms2-2
            - liborc-0.4-0
            - libraw16
            - libtiff5
        override-build: |
            cd server/plugin/plg_image_light/deps/
            gcc -Wall -c src/libresize.c -I/root/stage/include/ `pkg-config --cflags glib-2.0`
            ar rcs libresize.a libresize.o
            cp libresize.a libresize_linux_amd64.a
            gcc -Wall -c src/libtranscode.c -lraw -lraw_r
            ar rcs libtranscode.a libtranscode.o
            cp libtranscode.a libtranscode_linux_amd64.a
            cd -
            CGO_CFLAGS_ALLOW='-fopenmp'
            #  -linkmode external -extldflags -static
            go build -mod=vendor --tags "fts5" -ldflags "-X github.com/mickael-kerjean/filestash/server/common.BUILD_DATE=`date -u +%Y%m%d` -X github.com/mickael-kerjean/filestash/server/common.BUILD_REF=`git rev-parse HEAD`" -o $SNAPCRAFT_PART_INSTALL/bin/filestash server/main.go

apps:
    filestash-h31:
        command: bin/filestash
        daemon: simple
        environment:
            FILESTASH_CONFIG_DIR: $SNAP_COMMON/
            FILESTASH_CACHE_DIR: $SNAP_DATA/
            FILESTASH_LOG_DIR: $SNAP_DATA/
            FILESTASH_PUBLIC_DATA_DIR: $SNAP/
            LD_LIBRARY_PATH: $SNAP/lib:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
        plugs:
            - network
            - network-bind
            - removable-media
            - home
